### ISSUE TITLE
Home - Description text size

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/good_meadow#1]
### Location
Home screen 'about' area

### Description
The body texts looks huge. Let's make it the same size as the rest of the site's body text

### Screenshot
<img width="1241" alt="screen shot 2016-11-16 at 1 10 47 pm" src="https://cloud.githubusercontent.com/assets/17103891/20359527/49ee8c8a-abfe-11e6-8962-18e8145aeac8.png">

**Comment by tfuqua** [comment]
Updated to 16px to match other sites. Idk why I had it set to 22px   -__-

**Comment by agentdoublel** [comment]
Excellent!
