### ISSUE TITLE
Mobile: Logo isn't centered

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/good_meadow#2]
### Location
Global

### Description
Logo isnt centered in the screen

### Screenshot
![img_1587](https://cloud.githubusercontent.com/assets/17103891/20769829/7e8b375e-b711-11e6-8242-eea39ac08317.PNG)

**Comment by agentdoublel** [comment]
@tfuqua Still doesn't look centered. :(

**Comment by tfuqua** [comment]
How about now?
